[package]
name = "msm"
version = "1.2.0"
edition = "2018"

[dependencies]
icicle-cuda-runtime = { path = "../../../wrappers/rust/icicle-cuda-runtime" }
icicle-core = { path = "../../../wrappers/rust/icicle-core" }
icicle-bn254 = { path = "../../../wrappers/rust/icicle-curves/icicle-bn254" }
bincode = "1.3.3"
home = "0.5.9"
serde = "1.0.197"
msm-cuda = { git = "https://github.com/supranational/sppark", features = ["bn254"], tag = "v0.1.6", optional = true }
halo2curves = { version = "0.6.0", optional = true }
ark-bn254 = { version = "0.3.0", optional = true}
ark-ff = { version = "0.3.0", optional = true}

[features]
compare = ["halo2curves", "msm-cuda", "ark-bn254", "ark-ff", "icicle-bn254/arkworks"]
profile = []
